#!/usr/bin/env python3
"""
Setup script to help you configure API keys for Clustery.
This script will create a .env file with your API keys and test the setup.
"""

import os
import sys


def test_packages():
    """Test if required packages are installed."""
    print("\n📦 Checking required packages...")
    
    try:
        import openai
        print(f"✅ OpenAI package installed: {openai.__version__}")
        return True
    except ImportError:
        print("❌ OpenAI package not installed")
        print("   Install with: pip install openai")
        return False


def test_openai_connection(api_key):
    """Test OpenAI API connection."""
    print("\n🤖 Testing OpenAI API connection...")
    
    try:
        import openai
        client = openai.OpenAI(api_key=api_key)
        
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "Say hello"}],
            max_tokens=5
        )
        
        print(f"✅ OpenAI API working! Response: {response.choices[0].message.content}")
        return True
        
    except Exception as e:
        error_msg = str(e)
        if "429" in error_msg or "quota" in error_msg.lower() or "billing" in error_msg.lower():
            print(f"⚠️  OpenAI API test failed: Quota exceeded")
            print("   Your API key is valid, but you've hit your usage limit.")
            print("   Add credits at: platform.openai.com/account/billing")
            print("   The key is saved - you can use it once you have credits.")
            return None  # Not a failure, just a warning
        else:
            print(f"❌ OpenAI API test failed: {e}")
            return False


def create_env_file():
    """Create .env file with API keys."""
    
    print("🔑 Clustery API Keys Setup")
    print("=" * 50)
    print("This script will help you set up your API keys.")
    print("Get your OpenAI key from: platform.openai.com/api-keys")
    print()
    
    # Check if packages are installed first
    if not test_packages():
        print("\n⚠️  Please install the OpenAI package first:")
        print("   pip install openai")
        print("\nThen run this script again.")
        return False
    
    # Get API keys from user
    openai_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()
    
    if not openai_key:
        print("\n⚠️  No API key entered. Creating .env file with placeholder...")
        openai_key = 'your_openai_api_key_here'
    
    # Create .env file content
    env_content = f"""# LLM API Configuration
# Generated by setup_api_keys.py

# OpenAI API Key (for GPT models)
OPENAI_API_KEY={openai_key}

# Optional: Default model preferences
DEFAULT_OPENAI_MODEL=gpt-4o-mini
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        
        if openai_key and openai_key != 'your_openai_api_key_here':
            print(f"✅ OpenAI API key set: {openai_key[:8]}...")
            
            # Test the API if a real key was provided
            print("\n" + "=" * 50)
            test_result = test_openai_connection(openai_key)
            
            print("\n" + "=" * 50)
            
            if test_result is True:
                print("\n🎉 Setup complete and tested!")
                print("\n🚀 Next step: Run the app")
                print("   streamlit run main.py")
            elif test_result is None:
                print("\n⚠️  Setup complete, but quota exceeded.")
                print("   Add credits to use AI features: platform.openai.com/account/billing")
                print("   Your key is saved and ready to use once you add credits.")
            else:
                print("\n⚠️  Setup complete, but API test failed.")
                print("   Your API key may be invalid or you may need to check your internet connection.")
                print("   You can still try using the app - it will prompt you if there's an issue.")
        else:
            print("⚠️  OpenAI API key not set (using placeholder)")
            print("\nTo set your key later:")
            print("1. Edit the .env file")
            print("2. Or re-run this script")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False


def main():
    """Main setup function."""
    print()
    
    if os.path.exists('.env'):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    success = create_env_file()
    
    if success:
        print()
    else:
        print("\n❌ Setup failed. Please try again.")


if __name__ == "__main__":
    main()